# Generated by Django 3.2.7 on 2021-10-08 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Films', '0003_auto_20210930_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesname',
            name='user_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moviesname',
            name='actor_name',
            field=models.CharField(max_length=200),
        ),
    ]
